
 steps:
 # try pulling cached image if exists
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - 'docker pull gcr.io/$PROJECT_ID/$_IMAGE:latest || exit 0'

# setup environment variables
# this uses the current $_MODE to determine what .env file to keep,
# deletes the rest, and renames the appropriate .env.* file to .env
 - id: set-env-variables
   name: alpine:3
   entrypoint: sh
   args:
   - '-c'
   - '(mv .env.$_MODE .env && rm .env.*) || exit 0'

 # build the container image, using cached image if available
 - id: build-container-image
   name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA', '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE:latest', '.']

 # push the container image to Container Registry
 # pushes to both the $COMMIT_SHA tag and the "latest" tag for caching
 - id: push-image-to-registry
   name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker tag gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA gcr.io/$PROJECT_ID/$_IMAGE:latest &&
      docker push gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA &&
      docker push gcr.io/$PROJECT_ID/$_IMAGE:latest

 # Deploy container image to Cloud Run
 - id: deploy-to-cloud-run
   name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - '$_CLOUD_RUN_SERVICE'
   - '--image'
   - 'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA'
   - '--region'
   - '$_REGION'
   - '--platform'
   - 'managed'
   - '--port'
   - '80'
   - '--allow-unauthenticated'
   - '--service-account'
   - '$_SERVICE_ACCOUNT'
 substitutions:
   _CLOUD_RUN_SERVICE: 'send-app'
   _IMAGE: 'send-app'
   _REGION: 'europe-west1'
   _SERVICE_ACCOUNT: ''
   _MODE: ''
 images:
 - 'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA'
 - 'gcr.io/$PROJECT_ID/$_IMAGE:latest'
# timeout: 900s
